import { describe, it, expect } from 'vitest';
import { generateReport, type ReportOptions } from './generateReport';
import { makeTask, makeSprint, makeGap } from '@/test/factories';

const baseOpts: ReportOptions = {
  sprintIds: [],
  dateFrom: null,
  dateUntil: null,
  includeGaps: true,
  includeStats: true,
};

describe('generateReport', () => {
  it('produces a header and footer with no data', () => {
    const report = generateReport([], [], [], baseOpts);
    expect(report).toContain('# Performance Report');
    expect(report).toContain('Generated by WorkLog');
    expect(report).toContain('_No completed tasks in this period._');
  });

  it('lists completed tasks with priority, points, and tags', () => {
    const tasks = [
      makeTask({
        title: 'Refactor auth',
        status: 'done',
        priority: 'high',
        story_points: 5,
        tags: ['backend'],
        completed_at: '2026-05-10T00:00:00.000Z',
      }),
    ];
    const report = generateReport(tasks, [], [], baseOpts);
    expect(report).toContain('Completed Work (1 tasks)');
    expect(report).toContain('[HIGH]');
    expect(report).toContain('**Refactor auth**');
    expect(report).toContain('5 pts');
    expect(report).toContain('backend');
  });

  it('excludes non-done tasks from completed work', () => {
    const tasks = [
      makeTask({ title: 'done one', status: 'done' }),
      makeTask({ title: 'wip one', status: 'in_progress' }),
    ];
    const report = generateReport(tasks, [], [], baseOpts);
    expect(report).toContain('done one');
    expect(report).toContain('In Progress (1 tasks)');
    expect(report).toContain('wip one');
  });

  it('includes summary stats with delivered points', () => {
    const tasks = [
      makeTask({ status: 'done', story_points: 3 }),
      makeTask({ status: 'done', story_points: 2 }),
    ];
    const report = generateReport(tasks, [], [], baseOpts);
    expect(report).toContain('## Summary');
    expect(report).toContain('**Tasks completed:** 2');
    expect(report).toContain('**Story points delivered:** 5');
  });

  it('omits the summary when includeStats is false', () => {
    const report = generateReport([], [], [], { ...baseOpts, includeStats: false });
    expect(report).not.toContain('## Summary');
  });

  it('scopes tasks by selected sprint', () => {
    const sprint = makeSprint({ id: 'sp1', name: 'Sprint One' });
    const tasks = [
      makeTask({ title: 'in sprint', status: 'done', sprint_id: 'sp1' }),
      makeTask({ title: 'out of sprint', status: 'done', sprint_id: null }),
    ];
    const report = generateReport(tasks, [sprint], [], { ...baseOpts, sprintIds: ['sp1'] });
    expect(report).toContain('in sprint');
    expect(report).not.toContain('out of sprint');
    expect(report).toContain('Sprint One');
  });

  it('includes open gaps sorted by recurrence and resolved gaps', () => {
    const gaps = [
      makeGap({ title: 'rare gap', recurrence: 1 }),
      makeGap({ title: 'frequent gap', recurrence: 4 }),
      makeGap({ title: 'fixed gap', resolved: true, resolved_at: '2026-05-01T00:00:00.000Z' }),
    ];
    const report = generateReport([], [], gaps, baseOpts);
    expect(report).toContain('Knowledge Gaps & Learning Areas');
    expect(report).toContain('frequent gap');
    expect(report).toContain('×4');
    expect(report).toContain('~~fixed gap~~');
    // frequent (recurrence 4) should appear before rare (recurrence 1)
    expect(report.indexOf('frequent gap')).toBeLessThan(report.indexOf('rare gap'));
  });

  it('omits gaps section when includeGaps is false', () => {
    const gaps = [makeGap({ title: 'hidden gap' })];
    const report = generateReport([], [], gaps, { ...baseOpts, includeGaps: false });
    expect(report).not.toContain('hidden gap');
  });

  it('filters completed tasks by date range', () => {
    const tasks = [
      makeTask({ title: 'in range', status: 'done', completed_at: '2026-05-10T00:00:00.000Z' }),
      makeTask({ title: 'too early', status: 'done', completed_at: '2026-01-01T00:00:00.000Z' }),
    ];
    const report = generateReport(tasks, [], [], {
      ...baseOpts,
      dateFrom: '2026-05-01',
      dateUntil: '2026-05-31',
    });
    expect(report).toContain('in range');
    expect(report).not.toContain('too early');
  });
});
